### ISSUE TITLE
Create setup for a dedicated postgresql server setup with instruction

### ISSUE THREAD

**Issue by sweemeng** [Sinar/popit_ng#110]
This is for used in docker setup for a dedicated postgresql container

**Comment by leowmjw** [comment]
@sweemeng I can handle this; just give me a general pointer on things needed (e.g do I just change to point to postgres and run manage.py migrate)

**Comment by sweemeng** [comment]
1) Bootstrap.sh have the user setup for popit user
2) Make sure pg_hba.conf is configured so that popit user can access from an ip address,

**Comment by sweemeng** [comment]
move to https://github.com/Sinar/popit_ng-docker
