### ISSUE TITLE
Create setup for a dedicated elasticsearch server setup with instruction

### ISSUE THREAD

**Issue by sweemeng** [Sinar/popit_ng#111]
this is for docker setup for elasticsearch to be used by popit_ng service

**Comment by leowmjw** [comment]
@sweemeng I can help with this; just give me a general direction which scripts / hook I should hit to start indexing/reindexing/nuclear blow up etc.

**Comment by sweemeng** [comment]
1) the reindex command is on popit instance
2) for this server it is a matter of making sure elasticsearch run as a daemon. 
https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-service.html

**Comment by sweemeng** [comment]
move to https://github.com/Sinar/popit_ng-docker
