### ISSUE TITLE
Allow raw (read-only) Elasticsearch query

### ISSUE THREAD

**Issue by leowmjw** [Sinar/popit_ng#132]
Anything query officially documented in Elasticsearch (read-only actions); since all the fields are already indexed by default.  Might as well be able to get some return from it.

Also, allow to choose which fields to be returned (e.g might only want the primary ID), and can choose if want the facet portion returned (not returned by default)

Alternatively (if need the lock down), request via special parameter (e.g view=search); return a slim output with the needed primary IDs but with facets.

**Comment by sweemeng** [comment]
don't close first, raw search do not require doc type...

**Comment by sweemeng** [comment]
implemented closing
