### ISSUE TITLE
Post Membership should have Organization ID

### ISSUE THREAD

**Issue by kaerumy** [Sinar/popit_ng#134]
eg, Fifth Cabinet of Najib Razak
http://popit.sinarproject.org/organizations/edit/55b72847916cff2b6d55ab7f

**Comment by kaerumy** [comment]
Example of Post Membership without  Organization http://popit.sinarproject.org/memberships/edit/55b759ffdfea92985dfeab42

**Comment by sweemeng** [comment]
implemented in #147
Anytime a membership only created with post and person, and post is linked to organization. Membership organization field will use post organization. If membership is update, and organization is null/None, and post have organization linked, membership will link to that organization.

BTW, if you supply organization on create and update, they will not override the field.

I added a script to convert the existing data.

Please verify

**Comment by sweemeng** [comment]
close implemented
