### ISSUE TITLE
Unable to search for Organizations deemed Parliament

### ISSUE THREAD

**Issue by leowmjw** [Sinar/popit_ng#136]
Do NOT Work:
```
http://api.popit.sinarproject.org/en/search/organizations?q=name:parliament
```

Works:
```
http://api.popit.sinarproject.org/en/search/organizations?q=name:cabinet
```

**Comment by sweemeng** [comment]
Need to find ID of the organization

**Comment by kaerumy** [comment]
I'll look into this, in a bit when I get back to cleaning up Malaysian parliament data.

**Comment by kaerumy** [comment]
Fixed to help improve search results, by adding in abstract text including both house of represenatives and dewan rakyat and upper house and parliament.  Also added Dewan Rakyat in other names even though it's Malay to help with results.
