### ISSUE TITLE
Language neutral fields are not indexed for other languages

### ISSUE THREAD

**Issue by kaerumy** [Sinar/popit_ng#171]
When a language field for example hluttaw_identifier in English is updated or added, it is not indexed for other available languages automatically.

eg.

http://api.openhluttaw.org/en/search/persons?q=%22UPMP-02-0001%22

returns no results for mn

http://api.openhluttaw.org/mn/search/persons?q=%22UPMP-02-0001%22

**Comment by kaerumy** [comment]
When updating content in mn, it doesn't seem to reindex the fields either.

**Comment by sweemeng** [comment]
ORM might consider entity not translated to a language as not exist.

**Comment by kaerumy** [comment]
Looks like it's working now, with the right language code of MY instead of MM http://api.openhluttaw.org/my/search/persons?q=UPMP-02-0026
