### ISSUE TITLE
Updating "name" field for person, also updates "family name"

### ISSUE THREAD

**Issue by kaerumy** [Sinar/popit_ng#172]
http://api.openhluttaw.org/en/persons/f2c3e4452e844ef1afc44e6e7765bf0a

![image](https://cloud.githubusercontent.com/assets/1060743/16508088/f1db5a18-3f61-11e6-867b-d4167ca22d84.png)

**Comment by sweemeng** [comment]
added, and tested deployed. waiting verify. 

Should would, but i did not write test which will bite me

**Comment by sweemeng** [comment]
fixed deployed. minimum fix
