### ISSUE TITLE
Ampersand & character in search string not escaped/fails

### ISSUE THREAD

**Issue by kaerumy** [Sinar/popit_ng#173]
Example query:

http://api.openhluttaw.org/en/search/organizations?q=%22Amyotha%20Hluttaw%20International%20Relations,%20Inter-parlimentary%20Relationship%20&%20Cooperation%20Committee%22

string: 

Amyotha Hluttaw International Relations, Inter-parlimentary Relationship & Cooperation Committee

**Comment by sweemeng** [comment]
fixed in #154

**Comment by sweemeng** [comment]
we have this in request boody search. Complicated query should use that, as elasticsearch have better support on escaping special character there
