### ISSUE TITLE
Flat results can be very long for organizations with lots of members

### ISSUE THREAD

**Issue by kaerumy** [Sinar/popit_ng#176]
It is really convenient to make one request such as an organiation and get all the details of memberships, posts and persons in one go. The results though can be very long if an organization has a lot of memberships such as a political party.

It can lead to very large results. Does the benefit/simplicity outweigh the benefits?

**Comment by kaerumy** [comment]
Example query http://api.popit.sinarproject.org/en/search/organizations?q=name:Malaysian%20Chinese%20Association result is 2.9MB

**Comment by sweemeng** [comment]
Pro
1) It make search easy. 
2) It make request easy
3) Very nice for caching the request is simpler

**Comment by geodome** [comment]
You could return an iterator, just like Elasticsearch.

**Comment by kaerumy** [comment]
A parameter maybe? eg. ?nested=[true|false|

**Comment by sybreon** [comment]
If you give people an option, it will be abused. They will just default to nested=true to be safe, which defeats the purpose. I think that the iterator option, is better.

**Comment by chrislo2004** [comment]
UX part: Flat search shows a reminder for refining searches plus educating them at the same time, and ...not returning a result until they refine it. so... means {Flat search>education...leading to> refined search}

**Comment by geodome** [comment]
This is the Elasticsearch iterator. It is actually called Scroll.

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html

**Comment by chrislo2004** [comment]
Scroll, the name sounds like its character(though its not real time). I guess its like reading a paragraph in facebook and then they have the "read on" button that displays more paragraphs. Well you can have a flat search query that may search all results, but you can also have it to show only the top 100 rows of results.

**Comment by geodome** [comment]
Popit isn't supposed to be real-time search engine, unlike Elasticsearch.

**Comment by sweemeng** [comment]
Turns out that 600+ membership is enough to cause and error 500 for fetching organization id 53633b5a19ee29270d8a9ecf(that's House of Representative btw). 

```
In [1]: from popit.models import *

In [2]: organization = Organization.objects.language("en").get(id="53633b5a19ee29270d8a9ecf")

In [3]: organization.name
Out[3]: u'House of Representatives'

In [4]: organization.memberships.language("en").count()
Out[4]: 679
```

**Comment by sweemeng** [comment]
Cargografias team prefer that data is one page. To make the size of data return from single page reasonable, result should be flattened. Cargografias query each entity individually. So instead of fetching memberships from person object, fetch memberships with same id in person_id .

**Comment by sweemeng** [comment]
implementation in #243

**Comment by sweemeng** [comment]
Close as #243 implemented
