### ISSUE TITLE
other_names for organizations are not indexed

### ISSUE THREAD

**Issue by kaerumy** [Sinar/popit_ng#177]
http://api.popit.sinarproject.org/en/search/organizations?q=other_names:MCA

Use case for this to be able to search for abbreviations eg. MCA, UMNO, 1MDB stored as other names.

**Comment by kaerumy** [comment]
Related to #80

**Comment by sweemeng** [comment]
Correct  query is 
http://api.popit.sinarproject.org/en/search/organizations?q=other_names.name:MCA

OtherName is an object, use entity.key method to search for object

**Comment by sweemeng** [comment]
http://api.popit.sinarproject.org/en/search/persons?q=name:Najib&minify=True

othername field exist.
