### ISSUE TITLE
Cannot update on_behalf_of_id field for memberships

### ISSUE THREAD

**Issue by kaerumy** [Sinar/popit_ng#181]
example: http://api.openhluttaw.org/en/memberships/d9c69df20a4e4f7eb335dbc0c3537736

payload tries to set e67bf2cdb4ff4ce89167cba3a514a6df
successful result still shows old id of 549164f7390c447cb1e7af3fdab2a019

Example:

payload:
`
{'person_id': u'96ec026618d04317a54ba0a0fd37342d', 'organization_id': u'897739b2831e41109713ac9d8a96c845', 'post_id': u'05956eb75d734bb38b4681a53099fe3c', 'on_behalf_of_id': 'e67bf2cdb4ff4ce89167cba3a514a6df'}
`

result:
`
{"result":{"id":"d9c69df20a4e4f7eb335dbc0c3537736","person":{"id":"96ec026618d04317a54ba0a0fd37342d","other_names":[],"identifiers":[{"id":"328d2c0652fa47c0a90ecc28fcfdc478","links":[],"identifier":"UPMP-02-0139","created_at":"2016-06-07T11:03:48.696770Z","updated_at":"2016-06-07T11:03:48.696809Z","scheme":"identifier__hluttaw","language_code":"en"}],"birth_date":"1944-04-06","death_date":null,"links":[],"contact_details":[],"email":null,"image":null,"created_at":"2016-06-07T11:03:48.686275Z","updated_at":"2016-06-30T13:46:45.120116Z","name":"Ohn Kyaw","family_name":"Ohn Kyaw","given_name":null,"additional_name":null,"honorific_prefix":"Sai","honorific_suffix":null,"patronymic_name":null,"sort_name":null,"gender":"male","summary":"","biography":"","national_identity":"Shan","language_code":"en"},"person_id":"96ec026618d04317a54ba0a0fd37342d","organization":{"id":"897739b2831e41109713ac9d8a96c845","parent_id":null,"founding_date":null,"dissolution_date":null,"links":[],"contact_details":[],"image":null,"created_at":"2016-06-07T07:38:21.476816Z","updated_at":"2016-06-07T07:38:21.476859Z","area":null,"name":"Amyotha","classification":null,"abstract":null,"description":null,"language_code":"en"},"organization_id":"897739b2831e41109713ac9d8a96c845","member":null,"member_id":null,"on_behalf_of":{"id":"549164f7390c447cb1e7af3fdab2a019","parent_id":null,"founding_date":null,"dissolution_date":null,"links":[],"contact_details":[],"image":null,"created_at":"2016-06-24T16:56:14.689608Z","updated_at":"2016-06-24T16:56:14.689653Z","area":null,"name":"Shan Nationalities League for Democracy Party","classification":null,"abstract":null,"description":null,"language_code":"en"},"on_behalf_of_id":"549164f7390c447cb1e7af3fdab2a019","area":null,"area_id":null,"post":{"id":"05956eb75d734bb38b4681a53099fe3c","organization_id":"897739b2831e41109713ac9d8a96c845","area_id":null,"start_date":null,"end_date":null,"contact_details":[],"links":[],"created_at":"2016-06-13T08:58:19.319002Z","updated_at":"2016-06-13T08:58:19.319049Z","label":"Shan-4","role":null,"language_code":"en"},"post_id":"05956eb75d734bb38b4681a53099fe3c","contact_details":[],"links":[],"start_date":"2016-02-03","end_date":null,"created_at":"2016-06-27T04:33:01.038818Z","updated_at":"2016-06-30T14:25:30.819751Z","label":null,"role":"MP","language_code":"en"}}
`

**Comment by sweemeng** [comment]
Funny. It is implemented. Lemme dig in further

```python
if on_behalf_of_id:
            on_behalf_of = Organization.objects.untranslated().get(id=on_behalf_of_id)
            instance.on_behalf_of = on_behalf_of
```

**Comment by kaerumy** [comment]
This function will work, but the problem is that on_behalf_of_id value itself is not updated to new value when new on_behalf_of_id  membership value is updated

**Comment by sweemeng** [comment]
That code snippet is from the update function.

**Comment by sweemeng** [comment]
implemented, tested and deployed. 

waiting for @kaerumy to test before closing

**Comment by kaerumy** [comment]
Fixed with test use case

**Comment by kaerumy** [comment]
re-opening, it seems that on_behalf_of: is no longer showing the nested organization details, but id again.

Regression?

**Comment by kaerumy** [comment]
Seems that openhluttaw instance hasn't been updated yet

**Comment by sweemeng** [comment]
implemented with unittest
