### ISSUE TITLE
When translation for organization name added, org nested in other entries are not

### ISSUE THREAD

**Issue by kaerumy** [Sinar/popit_ng#182]
Example:

Organization with lang 'my' name updated:
http://api.openhluttaw.org/my/organizations/897739b2831e41109713ac9d8a96c845

Person with lang 'my' still shows organization 'en'
http://api.openhluttaw.org/my/persons/f2c3e4452e844ef1afc44e6e7765bf0a

**Comment by sweemeng** [comment]
Need to override the representation. Could take sometime

**Comment by sweemeng** [comment]
deployed, tested ok. waiting for @kaerumy to verify
