### ISSUE TITLE
Nested posts for memberships not translated if translation available

### ISSUE THREAD

**Issue by kaerumy** [Sinar/popit_ng#195]
http://api.openhluttaw.org/my/posts/fc6c49b342754fea84b957bab98efb8d

Nested post in membership showing language en

**Comment by sweemeng** [comment]
The language is set wrongly. Need to use language set in serializer, not in the entity instance

**Comment by sweemeng** [comment]
cannot just set language because language is set either from database query or set in instantiating serializer. need to check if language is set before setting in to_represetntative method

**Comment by sweemeng** [comment]
Code is implemented. closing. Reopen if issue still happen
