### ISSUE TITLE
Updating labels for contact_detail items always updates en

### ISSUE THREAD

**Issue by kaerumy** [Sinar/popit_ng#205]
Test URL:

http://api.openhluttaw.org/my/persons/5eaa6ea49fb1415a86a04691a9eb8921/contact_details/7a5b5c4f0d6a43c2a3e84261920841de

```
payload = {'label': '\xe1\x80\x96\xe1\x80\xaf\xe1\x80\x94\xe1\x80\xba\xe1\x80\xb8\xe1\x80\x94\xe1\x80\xb6\xe1\x80\x95\xe1\x80\xab\xe1\x80\x90\xe1\x80\xba'}
```

When updating with my url, en is updated instead while my values stays the same 'null'

**Comment by kaerumy** [comment]
Priority issue, because openhluttaw  want to have at least all the details for person in Burmese for beta

**Comment by sweemeng** [comment]
fix on a sub issue on #192 need more testing

**Comment by sweemeng** [comment]
In production now. please test before close

**Comment by sweemeng** [comment]
in production with unittest.  no one complain closing
