### ISSUE TITLE
Implement relation class

### ISSUE THREAD

**Issue by sweemeng** [Sinar/popit_ng#221]
This will be a new entity find out the spec and implement this as models and serializer objects.

**Comment by jpmckinney** [comment]
If you discover any issues with the [schema](https://github.com/influencemapping/whos_got_dirt-gem/blob/master/schemas/schema.json#L132-L212), we can adjust as needed and create a page in the Popolo documentation.

**Comment by sweemeng** [comment]
@jpmckinney got it thanks
