### ISSUE TITLE
Open Hluttaw website search by MP township, by Committee, returning duplicated results

### ISSUE THREAD

**Issue by OpenHluttawInfrastructure** [Sinar/popit_ng#236]
on the website search results showing different ways of duplicated results in terms of displayed results of MP profiles, also displayed count,

http://openhluttaw.info/en_US/person/?committeeId=5ef2e90de6ea44e8adf14893fbec5aa3

**Comment by OpenHluttawInfrastructure** [comment]
for both Open Hluttaw website, and Mobile app

**Comment by sweemeng** [comment]
On production data for malaysia data

```
for i in temp["hits"]["hits"]:
    print(i["_source"]["updated_at"])
   ....:     
2016-10-26T05:56:18.466506Z
2016-10-26T05:56:18.466506Z
2016-08-18T02:52:39.658559Z
2016-10-26T05:56:18.466506Z
2016-10-26T05:53:56.541840Z
2016-10-26T05:56:18.466506Z
```

Check last updated at on indexing might be a good idea.

**Comment by sweemeng** [comment]
let see if we need a clean up script vs check

**Comment by sweemeng** [comment]
This is happening in the bulk indexing code. We switch from individual indexing to bulk indexing

**Comment by sweemeng** [comment]
Try see if issue is due to https://github.com/celery/celery/issues/2481

**Comment by OpenHluttawInfrastructure** [comment]
I am sure you will look at this too when you can @kaerumy . Actually I forgot to report you, it was like fixed during one of the purge and reindex rounds you did during committee membership updated, I noticed count and actual displayed number of MPs were correct. But with the latest and current status, the problem is back, pls see for yourself by choosing one committee from a menu on the website.

**Comment by sweemeng** [comment]
related #218

**Comment by sweemeng** [comment]
implemented and deployed
