### ISSUE TITLE
some MP details showing wrong committees

### ISSUE THREAD

**Issue by OpenHluttawInfrastructure** [Sinar/popit_ng#237]
some MPs, like this one -

http://openhluttaw.info/en_US/person-detail/?personId=9066c97c09b0455ba33e51781d805e5e

showing the committee memberships he is not belong to. This guy is from Upper house (အမျိုးသားလွှတ်တော်), but a lower house committee is also being displayed.
Like this -
"Amyotha Hluttaw Government’s Guarantees, Pledges and Undertakings Vetting Committee, 
Pyithu Hluttaw Government’s Guarantees, Pledges and Undertakings Vetting Committee"

But actually, more importantly, in the list of Committees to choose from, there is no "Pyithu Hluttaw Government’s Guarantees, Pledges and Undertakings Vetting Committee".

**Comment by kaerumy** [comment]
Need to verify whether data or cache issue. Will look into it.

**Comment by OpenHluttawInfrastructure** [comment]
for both Open Hluttaw website, and Mobile app

**Comment by kaerumy** [comment]
@OpenHluttawInfrastructure does it look OK now?

**Comment by OpenHluttawInfrastructure** [comment]
Yes, it's fixed! @kaerumy
