### ISSUE TITLE
Elastic search problem, showing "Authentication credentials were not provided."

### ISSUE THREAD

**Issue by OpenHluttawInfrastructure** [Sinar/popit_ng#240]
http://api.openhluttaw.org/advancesearch/persons/?size=10&from=0

POST => {"query":{"bool":{"minimum_should_match":1,"must":[{"term":{"language_code":"my"}}],"should":[{"term":{"memberships.post_id":"f0ed18d11f4d45cb9213e035e25f77a4"}},{"term":{"memberships.post_id":"a9d6c62db0bf40f7a4c8b15a9f005788"}}]}}}

It is ok in last month.I can get data.

Now it is showing => 
{
"detail": "Authentication credentials were not provided."
}

**Comment by OpenHluttawInfrastructure** [comment]
we need this for Open Hluttaw mobile app.

**Comment by sweemeng** [comment]
definitely a regression. I don't know why though
