### ISSUE TITLE
Posting to Areas: Response 400

### ISSUE THREAD

**Issue by kay-wong** [Sinar/popit_ng#249]
Payload: {"identifier":"p003 ","name":"arau","classification":"Parliamentary Constituency"}

**Comment by sweemeng** [comment]
Essentially 2 issue
1) I did not post errors in the error message. 
2) it have only 20 character limit. I will expand it.

**Comment by sweemeng** [comment]
Verified on our instance. Checking on openhluttaws

**Comment by sweemeng** [comment]
implemented, tested and deployed
