### ISSUE TITLE
POST/PUT payload with image field returns response 200, but it's never updated on the DB.

### ISSUE THREAD

**Issue by kay-wong** [Sinar/popit_ng#253]
url = 'http://api.popit.sinarproject.org/en/organizations/c41b2c95961f472b94d83db8a3e7d562'
payload = {'image': "https://upload.wikimedia.org/wikipedia/commons/9/91/MY_Logo_PPBM.png"}

**Comment by sweemeng** [comment]
to be fixed in #254
