### ISSUE TITLE
Making a put request to mm languge code updates en language code instead for Areas class

### ISSUE THREAD

**Issue by kay-wong** [Sinar/popit_ng#260]
url_mm = 'http://api.openhluttaw.org/mm/areas/ed1c73ee93f94730819484bc018031b5'
payload= {'name': 'ကနီမဲဆန္ဒနယ်'}
r = requests.put(url_mm, headers=headers, json=payload)

Outputs 
r.json:  {'results': {'children': [],
  'classification': 'Parliamentary Constituency',
  'created_at': '2017-05-28T02:54:05.378291Z',
  'id': 'ed1c73ee93f94730819484bc018031b5',
  'identifier': None,
  'language_code': 'mm',
  'links': [],
  'name': 'ကနီမဲဆန္ဒနယ်',
  'parent': None,
  'parent_id': None,
  'updated_at': '2017-05-28T03:07:52.814099Z'}}

r.json returns for language code mm, but reloading in browser and making a get request shows that en is updated, not mm. Doesn't seem to be an issue for persons class.

**Comment by sweemeng** [comment]
I works in test environment and the code with myanmar is synced with master. I go dig deeper

**Comment by sweemeng** [comment]
deploy verify thanks
