### ISSUE TITLE
Contact field is not available in search result

### ISSUE THREAD

**Issue by sweemeng** [Sinar/popit_ng#80]

**Comment by sweemeng** [comment]
related to #75

**Comment by sweemeng** [comment]
fix and tested

http://api.popit.sinarproject.org/en/search/organizations/?q=id:9ee06e9e444144c5ba286892feeed894. 
@kaerumy verify?

**Comment by kaerumy** [comment]
General search is fixed, but not by label http://api.popit.sinarproject.org/en/search/organizations?q=contact_details:@sinarproject.org

**Comment by sweemeng** [comment]
http://api.popit.sinarproject.org/en/search/persons?q=name:Najib&minify=True

Contact details is in
