### ISSUE TITLE
Enable Django REST Swagger

### ISSUE THREAD

**Issue by leowmjw** [Sinar/popit_ng#96]
Can a Swagger Doc be generated automatically/semi-automatically using "Django REST Swagger" as per below:

http://www.django-rest-framework.org/topics/documenting-your-api/#documenting-your-api

I tried the changes below and it shows the Swagger docs page the but the automatic introspection does not seem to work; maybe I left out something?

```
leow$ git diff
diff --git a/popit_ng/settings.py b/popit_ng/settings.py
index 4a7a520..dbd06a9 100644
--- a/popit_ng/settings.py
+++ b/popit_ng/settings.py
@@ -47,6 +47,7 @@ INSTALLED_APPS = (
     'popit',
     'popit_search',
     'corsheaders',
+    'rest_framework_swagger',
 )

 MIDDLEWARE_CLASSES = (
diff --git a/popit_ng/urls.py b/popit_ng/urls.py
index 777770f..4563279 100644
--- a/popit_ng/urls.py
+++ b/popit_ng/urls.py
@@ -24,6 +24,7 @@ from rest_framework.authtoken import views as token_view

 urlpatterns = [
     url(r'^admin/', include(admin.site.urls)),
+    url(r'^docs/', include('rest_framework_swagger.urls')),
 ]
```

**Comment by sweemeng** [comment]
Could be because I don't use a router to define routes. Instead manually define route like a standard django app. I do it due to the way our URL works, /<language>/<entity>/<entity_id>. It does not work as well with the standard way to setup an endpoint in django rest framework

**Comment by sweemeng** [comment]
django rest framework documentations recommend http://drfdocs.com/

**Comment by sweemeng** [comment]
turns out that we need to do #127 before this can work properly

**Comment by sweemeng** [comment]
tested and deployed
