### ISSUE TITLE
When logging in via "vagrant ssh"; user should be in /vagrant

### ISSUE THREAD

**Issue by leowmjw** [Sinar/popit_ng#97]
Make it so that when login via "vagrant ssh" that the user is automatically in the folder containing the code so that the documentation to setup system reads correctly to a Django newbie (me!):

```
leow$ git diff bootstrap.sh 
diff --git a/bootstrap.sh b/bootstrap.sh
index dfe4c0c..c5d03ea 100644
--- a/bootstrap.sh
+++ b/bootstrap.sh
@@ -12,3 +12,5 @@ apt-get install -y openjdk-7-jre unzip
 wget https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distri
 unzip elasticsearch-2.1.0.zip
 
+# Ensure when login via shell it goes to the code
+echo -e "\ncd /vagrant" >>~/.bashrc
```

**Comment by sweemeng** [comment]
Tested after rebuilding image on vagrant, ssh do not automatically change directory to /vagrant

**Comment by sweemeng** [comment]
cd /vagrant is not added to .bashrc when VM is provisioned for the first time.

**Comment by sweemeng** [comment]
Also changing .bashrc is breaking my IDE's behavior. They expect helper script to be in /home/vagrant

**Comment by leowmjw** [comment]
Apologies; my bad, I only tested the execution of the bash command.  Forgot provisioning is happening as root.  Here's the corrected, and this time I tested in Vagrant :P

```
popit_ng_pr leow$ git diff
diff --git a/bootstrap.sh b/bootstrap.sh
index c5d03ea..175087b 100644
--- a/bootstrap.sh
+++ b/bootstrap.sh
@@ -13,4 +13,4 @@ wget https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/
 unzip elasticsearch-2.1.0.zip
 
 # Ensure when login via shell it goes to the code
-echo -e "\ncd /vagrant" >>~/.bashrc
+echo -e "\ncd /vagrant" >>/home/vagrant/.bashrc
```
