### ISSUE TITLE
Missing documentation for indexing Elasticsearch

### ISSUE THREAD

**Issue by leowmjw** [Sinar/popit_ng#98]
Did not see any docs on setting up the Elasticsearch instance; after I have setup the test data.

**Comment by sweemeng** [comment]
@leowmjw anythiing to add?

**Comment by leowmjw** [comment]
I would like

I am working on the docker image, so would be good to know
- How to inject in config via environment variables, as elasticsearch and postgres is on different machine
- How to trigger initial index and re-index

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Thu, Feb 4, 2016 at 7:44 PM -0800, "sweemeng" <notifications@github.com<mailto:notifications@github.com>> wrote:


@leowmjw<https://github.com/leowmjw> anythiing to add?

-

**Comment by sweemeng** [comment]
I create a new task for docker related setup and close this issue

**Comment by sweemeng** [comment]
Some of those are not implemented yet. Created issue to address the above issue
#110 #111 #112 and #113
